name: Node Express - Tests
on:
  push:
    branches: ['develop', 'release-*']

jobs:
  nodejs-express-integration:
    runs-on: ubuntu-latest

    env:
      PORT: 3002
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: test_database
      DB_PORT: 3306
          
    steps:
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USERNAME }} -p${{ env.DB_PASSWORD }}
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run-script test
          
      - name: SonarCloud Scan
        if: success()
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}
